# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95516f271f63cbefada64c8a3302c1ca"
name = "MontyPay Payment Gateway"
handle = "montypay-payment-gateway"
application_url = "https://montypaylive.fly.dev"
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "monty-pay-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_gateways,write_payment_sessions"

[auth]
redirect_urls = [
  "https://montypaylive.fly.dev/auth/callback",
  "https://montypaylive.fly.dev/auth/shopify/callback",
  "https://montypaylive.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://montypaylive.fly.dev/webhooks/app/uninstalled"

[pos]
embedded = false
